<?php

/*
 * Bear CMS addon for Bear Framework
 * https://bearcms.com/
 * Copyright (c) Amplilabs Ltd.
 * Free to use under the MIT license.
 */

return <<<'EOT'
var bearCMS=bearCMS||{};bearCMS.elementEvents=bearCMS.elementEvents||function(){if(void 0!==window.addEventListener&&void 0!==document.querySelectorAll&&"undefined"!=typeof IntersectionObserver){var e="data-bearcms-element-event",t=[],n=[],i=function(e,i){var r=n[t.indexOf(e)],o=function(e){var t=r.indexOf(e);-1!==t&&r.splice(t,1)},l=function(e){-1===r.indexOf(e)&&r.push(e)},s=function(e){return-1!==r.indexOf(e)};0===i?(l("not-visible"),e.getBoundingClientRect().top<0?l("is-above-viewport"):l("is-below-viewport"),o("visible"),o("fully-visible"),o("was-above-viewport"),o("was-below-viewport")):(s("is-above-viewport")&&l("was-above-viewport"),s("is-below-viewport")&&l("was-below-viewport"),o("not-visible"),o("is-above-viewport"),o("is-below-viewport"),1===i?(l("fully-visible"),l("fully-seen")):o("fully-visible"),l("visible"),l("seen")),r.sort()},r=[],o={},l=function(e,i,l){var s=l.split(" ",2);if(2===s.length){var v=s[0].trim().split("+"),a=s[1].trim(),u=l.substring(s[0].length+s[1].length+1).trim();"call"===a&&-1!==v.indexOf("not-visible")&&-1===v.indexOf("seen")&&v.push("seen");var f=t.indexOf(e),d=n[f],b=d.filter((function(e){return-1!==v.indexOf(e)})),c=f+"-"+i,w=b.join(",");if(void 0!==o[c]&&o[c][0]===w)return;var p=function(e){for(var t=0;t<e.length;t++){var n=e[t];if(-1===b.indexOf(n))return!1}return!0};if(o[c]=[w,b],"attribute"===a)p(v)?e.setAttribute(u,""):e.removeAttribute(u);else if("call"===a&&p(v)){if(0===v.filter((function(e){return"load"!==e&&"seen"!==e&&"fully-seen"!==e})).length){if(-1!==r.indexOf(c))return;r.push(c)}!function(e,t,n){if(null!==e&&""!==e)try{new Function("event",e).apply(t,[n])}catch(e){}}(u,e,new CustomEvent("visibilityChange",{detail:{states:d}}))}}},s=function(t){var n=t.getAttribute(e);if("*"===n)for(var i=t.attributes,r=0;r<i.length;r++){var o=i[r];0===o.name.indexOf(e+"-")&&l(t,o.name,o.value)}else l(t,e,n)},v=new IntersectionObserver((function(e){for(var t in e){var n=e[t],r=n.target;i(r,n.intersectionRatio),s(r)}}),{threshold:[0,1]}),a=function(){for(var i=document.querySelectorAll("["+e+"]"),r=0;r<i.length;r++){var o=i[r];if(-1===t.indexOf(o)){t.push(o),v.observe(o);var l=t.indexOf(o);n[l]=["load"],s(o)}}},u=!1,f=function(){u||(u=!0,"undefined"!=typeof MutationObserver&&new MutationObserver((function(){a()})).observe(document.querySelector("body"),{childList:!0,subtree:!0}))};document.addEventListener("readystatechange",()=>{f(),a()}),"complete"===document.readyState&&(f(),a())}else a=function(){};return{run:a}}();
EOT;
