<?php

/*
 * Bear CMS addon for Bear Framework
 * https://bearcms.com/
 * Copyright (c) Amplilabs Ltd.
 * Free to use under the MIT license.
 */

return <<<'EOT'
var bearCMS=bearCMS||{};bearCMS.elementEvents=bearCMS.elementEvents||function(){if(void 0!==window.addEventListener&&void 0!==document.querySelectorAll&&"undefined"!=typeof IntersectionObserver){var e=[],t=function(e,t,i){if(null!==e&&""!==e)try{new Function("event",e).apply(t,[i])}catch(e){}},i=new IntersectionObserver((function(e){for(var t in e){var i=e[t],n=i.target;o(n,i.intersectionRatio),l(n,"data-bearcms-visibility-change",v)}}),{threshold:[0,1]}),n=[],r=function(e,i){-1===n.indexOf(e)&&(n.push(e),t(i,e))},a=[],o=function(t,i){var n=e.indexOf(t),r=function(e){var t=a[n].indexOf(e);-1!==t&&a[n].splice(t,1)},o=function(e){-1===a[n].indexOf(e)&&a[n].push(e)},s=function(e){return-1!==a[n].indexOf(e)};0===i?(o("not-visible"),t.getBoundingClientRect().top<0?o("is-above-viewport"):o("is-below-viewport"),r("visible"),r("fully-visible"),r("was-above-viewport"),r("was-below-viewport")):(s("is-above-viewport")&&o("was-above-viewport"),s("is-below-viewport")&&o("was-below-viewport"),r("not-visible"),r("is-above-viewport"),r("is-below-viewport"),1===i?(o("fully-visible"),o("fully-seen")):r("fully-visible"),o("visible"),o("seen")),a[n].sort()},s=[],v=function(n,r,o){if(-1===e.indexOf(n)){e.push(n),i.observe(n);var v=e.indexOf(n);a[v]=[]}else{v=e.indexOf(n);var l=a[v],u=v+"-"+o;if(l.length>0){var f=l.join(",");if("undefined"!==s[u]&&s[u]===f)return;s[u]=f;var d=new CustomEvent("visibilityChange",{detail:{states:l}});t(r,n,d)}}},l=function(e,t,i){var n=e.getAttribute(t);if("*"===n)for(var r=e.attributes,a=0;a<r.length;a++){var o=r[a];0===o.name.indexOf(t+"-")&&i(e,o.value,o.name)}else i(e,n,t)},u=["data-bearcms-load","data-bearcms-visibility-change"],f=u.length,d=function(){for(var e=0;e<f;e++)for(var t=u[e],i=document.querySelectorAll("["+t+"]"),n=0;n<i.length;n++){var a=i[n];l(a,"data-bearcms-load",r),l(a,"data-bearcms-visibility-change",v)}},c=!1,b=function(){c||(c=!0,"undefined"!=typeof MutationObserver&&new MutationObserver((function(){d()})).observe(document.querySelector("body"),{childList:!0,subtree:!0}))};document.addEventListener("readystatechange",()=>{b(),d()}),"complete"===document.readyState&&(b(),d())}else d=function(){};var w=[];return{run:d,updateVisibilityAttributes:function(e,t,i){for(var n=t.detail.states,r=0;r<i.length;r++){var a=i[r],o="data-bearcms-vs-"+a;-1===n.indexOf(a)?e.removeAttribute(o):e.setAttribute(o,"")}},executeVisibilityCode:function(i,n,r){for(var a=e.indexOf(i),o=n.detail.states,s=0;s<r.length;s++){var v=r[s][0],l=r[s][1];if(v.filter((function(e){return-1!==o.indexOf(e)})).length===v.length){if(0===v.filter((function(e){return"seen"!==e&&"fully-seen"!==e})).length){var u=a+"-"+l;if(void 0!==w[u])continue;w[u]=1}t(l,i)}}}}}();
EOT;
